FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y software-properties-common

WORKDIR /app

COPY brokerFileManager /app/brokerFileManager
RUN chmod +x /app/brokerFileManager

EXPOSE 32002
CMD ./brokerFileManager
