apiVersion: apps/v1
kind: Deployment
metadata:
 name: broker-filemanager
 namespace: default
spec:
 replicas: 1
 selector:
  matchLabels:
   app: brokerfm
 template:
  metadata:
   labels:
    app: brokerfm
  spec:
   containers:
   - name: broker-container
     image: docker.io/alejandromontero1/brokerfilemanager:0.1v
     ports:
     - containerPort: 32002
